buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id 'com.android.application' version '8.0.0' apply false
}

apply plugin: 'com.android.application'
apply plugin: 'stringfog'

android {
    namespace "com.test.stringfog"
    compileSdk 31
    defaultConfig {
        applicationId "com.test.stringfog"
        minSdk 15
        targetSdk 28
        versionCode 1
        versionName "1.0"
    }
    buildFeatures {
        buildConfig = true
    }
}

stringfog {
    implementation 'com.github.megatronking.stringfog.xor.StringFogImpl'
    enable true
}