plugins {
    id "java-library"
    id "org.jetbrains.kotlin.jvm" version "1.8.21"
}

repositories {
    google()
    maven { url 'https://maven.aliyun.com/repository/central' }
    maven { url 'https://maven.aliyun.com/repository/google' }
    maven { url 'https://maven.aliyun.com/repository/public' }
    mavenLocal()
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()
    compileOnly 'com.android.tools.build:gradle:8.0.0'
    implementation project(':stringfog-core')
    implementation project(':stringfog-interface')

    testImplementation 'junit:junit:4.13.2'
    testImplementation gradleTestKit()
}

sourceSets {
    main {
        java {
            srcDir 'src/main/java'
        }
        resources {
            srcDir 'src/main/resources'
        }
    }
    test {
        java {
            srcDir 'src/test/java'
        }
        resources {
            srcDir 'src/test/resources'
        }
    }
}

tasks.withType(ProcessResources){
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
tasks.withType(Jar){
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

tasks {
    compileKotlin {
        kotlinOptions.jvmTarget = targetCompatibility
    }
    compileTestKotlin {
        kotlinOptions.jvmTarget = targetCompatibility
    }
}

// Generate plugin-classpath.txt for Gradle TestKit functional tests
task createPluginClasspathFile() {
    def outputDir = file("${buildDir}/resources/test")
    inputs.files(sourceSets.main.runtimeClasspath)
    outputs.dir(outputDir)
    doLast {
        outputDir.mkdirs()
        file("${outputDir}/plugin-classpath.txt").text = sourceSets.main.runtimeClasspath.join('\n')
    }
}

test {
    dependsOn(createPluginClasspathFile)
}

apply from: '../maven_local.gradle'

// The following is used for mavenCentral publish.
// apply from: '../maven_nexus.gradle'